### PR TITLE
Replaced `shipping_firstname` and `shipping_lastname` with `payment_f…

### PR DESCRIPTION
**Pull request by ashwch**
…irstname`and`shipping_lastname` respectively

### CODE REVIEW

**Comment by sunsys0** [comment]
Why was this change done or why was it necessary to change from shipping_firstname` and shipping_lastname to payment_firstname and shipping_lastname, were there any issues with it or what pl explain. Thank you.

**Comment by ashwch** [comment]
@sunsys0 Yes it is an issue, using `shipping_firstname` and `shipping_lastname` to get the buyer's first and last name  won't work for products with shipping disabled, in that case the name field on Instamojo form will show up as empty and buyer won't be able to make a payment.

**Comment by sunsys0** [comment]
Thank you for the reply so do you advice that I should reinstall this updated version of instamojo software on my opencart store and what about opencart version 15xx is there anything similar for that too and from where do I download the latest version of Instamojo for opencart ?

**Comment by ashwch** [comment]
@sunsys0 Yes, you should install the latest version. This issue was already fixed in 1.5.x a while ago but was pending for 2.0.x. You can download the extension from here: http://www.opencart.com/index.php?route=extension/extension/info&token=6bfda2c2803a1ea4e9776d2f82654ba9&extension_id=21984

**Comment by sunsys0** [comment]
Thank you Ashwini for your reply, I have updated the Instamojo software as suggested by you.

**Pull request merged**
